### PR TITLE
Complementary data version1

### PR DESCRIPTION
**Pull request by Pratichhya**
It is the first replica of the complementary data documentation for Copernicus Data Space ecosystem.

Need to recheck detail link for:
* BALTICSEA_ANALYSIS_FORECAST_BIO_003_007
* MULTIOBS_GLO_BIO_REP_015_005
* MULTIOBS_GLO_BIO_REP_015_006
* CAMS GLOBAL ADDITIONAL

### CODE REVIEW

**Comment by JanssenBrm** [comment]
For the Landsat 7 collection, it could make sense to repeat the product again in the table here. This would make it more consistent for the users.

**Comment by JanssenBrm** [comment]
The CMEMS page seems to be empty? (https://eu-cdse.github.io/documentation/pr-preview/pr-211/Data/CEMS.html)

**Comment by Pratichhya** [comment]
> For the Landsat 7 and 8 collections, it could make sense to repeat the product again in the table here. This would make it more consistent for the users.

Included the product column in Landsat7 and Landsat 8 too.

**Comment by Pratichhya** [comment]
> It looks like the "offered data" header is smaller then the ones below it.
> 
> image

Updated

**Comment by Pratichhya** [comment]
> The CMEMS page seems to be empty? (https://eu-cdse.github.io/documentation/pr-preview/pr-211/Data/CEMS.html)

It is Copernicus Emergency Management Service (CEMS), not the Marine one. The provided document didn't include any product details for this service.

**Comment by Pratichhya** [comment]
> @Pratichhya - On the VHR commercial data section, it is mentioned "Support Department". Can you request some more information as this could be unclear for users?

Sure @JanssenBrm I can.

**Pull request merged**
