### PR TITLE
Introductory display

### PR DESCRIPTION
**Pull request by Pratichhya**
This PR includes modification of page visualisation for the introductory page only.

### CODE REVIEW

**Comment by Pratichhya** [comment]
@KanerLev could you please help me confirm if I missed content when changing to this view in the introductory section: 
https://eu-cdse.github.io/documentation/pr-preview/pr-406/Data.html
https://eu-cdse.github.io/documentation/pr-preview/pr-406/APIs.html
https://eu-cdse.github.io/documentation/pr-preview/pr-406/Applications.html

Since the files and folders are rearranged in some cases, there can be a merged conflict, so we will have to merge when the changes are good to go and have fewer PRs.

**Comment by KanerLev** [comment]
> @KanerLev could you please help me confirm if I missed content when changing to this view in the introductory section: https://eu-cdse.github.io/documentation/pr-preview/pr-406/Data.html https://eu-cdse.github.io/documentation/pr-preview/pr-406/APIs.html https://eu-cdse.github.io/documentation/pr-preview/pr-406/Applications.html
> 
> Since the files and folders are rearranged in some cases, there can be a merged conflict, so we will have to merge when the changes are good to go and have fewer PRs.

Data:
1) the title: "ENVISAT- Medium Resolution Imaging Spectrometer (MERIS)" is missing
2) the title "Copernicus Emergency Management Service (CEMS)" is missing:

API:
1)**ON Demand Production API section** is missing:

Applications:
OK.

**Comment by Pratichhya** [comment]
> > @KanerLev could you please help me confirm if I missed content when changing to this view in the introductory section: https://eu-cdse.github.io/documentation/pr-preview/pr-406/Data.html https://eu-cdse.github.io/documentation/pr-preview/pr-406/APIs.html https://eu-cdse.github.io/documentation/pr-preview/pr-406/Applications.html
> > Since the files and folders are rearranged in some cases, there can be a merged conflict, so we will have to merge when the changes are good to go and have fewer PRs.
> 
> Data:
> 
> 1. the title: "ENVISAT- Medium Resolution Imaging Spectrometer (MERIS)" is missing
> 2. the title "Copernicus Emergency Management Service (CEMS)" is missing:
> 3. On Page three the title "
>    Please note that more details of these collections will be added in the near future." is for VHR Commercial Data. VHR Commercial Data is removed from the documentation a while ago. So in PR 406 it should be removed also.
> 
> API: 1)**ON Demand Production API section** is missing:
> 
> Applications: OK.

Thank you 😄. Updated as suggested. It should be fine once the page deployment is completed.

**Review by KanerLev — APPROVED** [review]
All looked good to me. Approved for merging.

**Pull request merged**
