### PR TITLE
CEMS update

### PR DESCRIPTION
**Pull request by Pratichhya**

### CODE REVIEW

**Comment by Pratichhya** [comment]
Patryk's suggestion: There is included list of each event stored by CEMS. There are hundreds of them, so I suggest creating some collapse list (or list of first ten events and search bar) within CEMS section.

**Comment by Pratichhya** [comment]
> Patryk's suggestion: There is included list of each event stored by CEMS. There are hundreds of them, so I suggest creating some collapse list (or list of first ten events and search bar) within CEMS section.

Included the document as a link to the events table. But since it is being fetched in string, rendering of the document is being an issue.

**Comment by Pratichhya** [comment]
Finally working well. Thank you @JanssenBrm

**Comment by Pratichhya** [comment]
@JanssenBrm a reminder :)

**Comment by JanssenBrm** [comment]
@Pratichhya  - I did some small updates on the styling and behaviour of the buttons. Let me know if you want to have it working differently. I did notice that the humanitarian tab is displaying "Extreme temperature" data. Is this expected? Just checking as the other tabs seems to be matching with the title of the table that is shown when clicking on them.

**Comment by Pratichhya** [comment]
@JanssenBrm The button looks much better now, and I am good with it.
Regarding the Extreme Temperature title, it was indicated in the provided sheet under Extreme Temperature but the Catalogue refers to Humanitarian. Thus, the button name was given as humanitarian(general) while keeping the title as provided.

**Review by JanssenBrm — APPROVED** [review]

**Pull request merged**
