### PR TITLE
Document machine-to-machine auth options in openeo

### PR DESCRIPTION
**Pull request by soxofaan**
Take 2 of PR #613  (targeting the publish branch this time)

(internal ref  eu-cdse/openeo-cdse-infra#233)

### CODE REVIEW

**Comment by soxofaan** [comment]
@Pratichhya  @KanerLev   I redid the PR as discussed, is there anything else I should include here?

Note that this PR is currently blocking https://github.com/eu-cdse/openeo-cdse-infra/issues/233

**Review by KanerLev — APPROVED** [review]
Thanks for taking this way (branching off from publish...).
No, I don't see anything else that needs to be included. This PR can be merged.

**Review by Pratichhya — APPROVED** [review]
No changes suggestion from me too :)

**Comment by soxofaan** [comment]
thanks!

**Pull request merged**
