### PR TITLE
Replicated Large scale processing page

### PR DESCRIPTION
**Pull request by Pratichhya**
The page available [here](https://github.com/openEOPlatform/documentation/blob/main/usecases/large-scale-processing/index.md) is replicated and included with minor changes such as:

- formatting
- removed `countries = europe[europe.name.isin(EU27)]` from the Python code since the dataframe no longer includes this term.
- Though I updated a few links, but the URL linking to openeo.org is left as it is. 
- Removed link to a [full example](https://github.com/openEOPlatform/openeo-classification/blob/main/src/openeo_classification/scripts/cropmap_eu27.py) from the openeoplatform repo

### CODE REVIEW

**Comment by Pratichhya** [comment]
@jdries since this is simply a replica of the existing markdown, I am not sure if there is much to change or add. However, please let me know if addition things needs to be taken into consideration before merging the PR.

**Comment by Pratichhya** [comment]
Hi @jdries a kind reminder

**Review by jdries — CHANGES_REQUESTED** [review]
There's a number of links to external resources, wouldn't it be better to include those images in the repo, just to be independent and avoid breakage?
 Also the link to execution options, doesn't quarto allow us to use relative links?

**Comment by Pratichhya** [comment]
> There's a number of links to external resources, wouldn't it be better to include those images in the repo, just to be independent and avoid breakage? Also the link to execution options, doesn't quarto allow us to use relative links?

Images are saved within the repository to avoid breakage. 
Yes, Quarto does allow relative links; it was just that we hadn't used it until now. Nevertheless, it is slowing being updated. (FYI, almost done for data section)

**Comment by Pratichhya** [comment]
@jdries, to resolve the conflict, I tried rebasing. But I also made a couple of mistakes, which I have reverted. 

I assume this PR should not have conflict or old content. However, should I create a new one if the list of commits is confusing?

**Comment by Pratichhya** [comment]
@jdries a kind reminder

**Comment by jdries** [comment]
@Pratichhya  the content of the large scale processing page looks fine.
The list of commits and changes is indeed confusing, and I can't immediately tell if this will result in problems, so up to you how to merge it in.

**Comment by Pratichhya** [comment]
> @Pratichhya the content of the large scale processing page looks fine. The list of commits and changes is indeed confusing, and I can't immediately tell if this will result in problems, so up to you how to merge it in.

I guess I would create a fresh PR with the relevant changes only. Since it's also been some while might have some more conflicts

**Pull request closed without merging**
