### PR TITLE
Updated Sentinel 3 collection based on product type

### PR DESCRIPTION
**Pull request by Pratichhya**

### CODE REVIEW

**Comment by Pratichhya** [comment]
Improved Sentinel 3 detail display based on internal suggestions. Band details on several Level 2 products are still not included as it was suggested that: In OLCI, SLSTR and SYN  Level2, it does not make sense to provide information on spectral bands, as this information is not included in the L2 products. Instead, we should provide a list of products as shown [here](https://sentinels.copernicus.eu/ca/web/sentinel/user-guides/sentinel-3-olci){target="_blank"}.

**Comment by jdries** [comment]
we need to be careful to not invent new concepts: 'sub-dataset' does not really exist.
I would stick as much as possible to collections+bands, and when really unavoidable use 'producttype' as an intermediate.

But as Sentinel-3 clearly introduces a large number of product types, we may need an interface that supports this a bit better. Let's maybe try to identify a few painpoints in the current design, and come up with a way to address this.

**Comment by Pratichhya** [comment]
> But as Sentinel-3 clearly introduces a large number of product types, we may need an interface that supports this a bit better. Let's maybe try to identify a few painpoints in the current design, and come up with a way to address this.

Trying to find an alternative solution in https://github.com/eu-cdse/documentation/tree/test_datavisualization

**Comment by Pratichhya** [comment]
Hi 

Thank you for your time and effort in reviewing this PR. Same as PR(https://github.com/eu-cdse/documentation/pull/216) it seems like it's now a bit mixed and messed up 😓 caused when trying to resolve the merging conflict.

There, I think it's good to close this and create a fresh one for a dedicated issue.

**Pull request closed without merging**
