### PR TITLE
Jupyter notebook first draft

### PR DESCRIPTION
**Pull request by Pratichhya**
Basic concept of Jupyter lab.

Still left to include more on data access using notebook.

### CODE REVIEW

**Comment by JanssenBrm** [comment]
I noticed that the user interface image does not contain visual references to the parts that are explained below the image.

**Comment by Pratichhya** [comment]
> I noticed that the user interface image does not contain visual references to the parts that are explained below the image.

@JanssenBrm, are you referring to the contextual tab or drag and drop functionality. Should I removed them?

**Comment by JanssenBrm** [comment]
My apologies for not being clear. In the "JupyterLab User Interface" section, there is a screen shot of the application. Right below this screenshot, there is an explanation of the different components (Main Work Area, Sidebar, ...). These components are referenced by numbers, but the screenshot itself does not contain any numbers.

**Comment by Pratichhya** [comment]
> My apologies for not being clear. In the "JupyterLab User Interface" section, there is a screen shot of the application. Right below this screenshot, there is an explanation of the different components (Main Work Area, Sidebar, ...). These components are referenced by numbers, but the screenshot itself does not contain any numbers.

Updated the image and rearranged as tips for feature not seen in the image

**Review by JanssenBrm — APPROVED** [review]

**Pull request merged**
