### PR TITLE
update of roadmap tables

### PR DESCRIPTION
**Pull request by abuiquoc**

### CODE REVIEW

**Comment by abuiquoc** [comment]
@Pratichhya can you help on "Complementary open data" part on Data table and "Data processing" part on API table? 
They should look like they are currently in production:
https://documentation.dataspace.copernicus.eu/Roadmap/DataTable.html
https://documentation.dataspace.copernicus.eu/Roadmap/APITable.html
This should be in the first column.

**Comment by KanerLev** [comment]
> @Pratichhya can you help on "Complementary open data" part on Data table and "Data processing" part on API table? They should look like they are currently in production: https://documentation.dataspace.copernicus.eu/Roadmap/DataTable.html https://documentation.dataspace.copernicus.eu/Roadmap/APITable.html This should be in the first column.

@abuiquoc I'll take over and help with these, starting from next week. Any urgency/deadline please let us know.

**Comment by abuiquoc** [comment]
@KanerLev thanks. I see that roadmap tables are now fixed. Can we merge this PR?

**Review by KanerLev — APPROVED** [review]
Fixed, merging

**Pull request merged**
