### PR TITLE
Update Subscriptions.qmd

### PR DESCRIPTION
**Pull request by pjasiakcf**

### CODE REVIEW

**Comment by KanerLev** [comment]
Hi @pjasiakcf, 

Considering this: https://dataspace.copernicus.eu/news/2024-6-17-website-update-26062024 , please wait for this website update to be over to merge PRs.

**Comment by pjasiakcf** [comment]
Hi @KanerLev,
thanks for the information. I will then wait for the website update.

**Comment by pjasiakcf** [comment]
@KanerLev can I merge this pull request?

**Comment by KanerLev** [comment]
@pjasiakcf sure, please go ahead.

**Pull request merged**
