### PR TITLE
mermaid_replaced_w_png

### PR DESCRIPTION
**Pull request by KanerLev**

### CODE REVIEW

**Comment by KanerLev** [comment]
Hi @jdries,

We realized mermaids causing actions to take hours and usually fail e.g. for openEO see https://github.com/eu-cdse/documentation/actions/runs/9674644637 (and for SentinelHub see: https://github.com/eu-cdse/documentation/pull/561#issuecomment-2191156515)

therefore we would like to replace these mermaid charts with their png equivalent at the moment. 
-For SentinelHub pages (see above) we had to replace them to merge an urgent PR.
-For openEO we are now bringing it to your attention.

 For the future if it's not strictly necessary to use mermaid script can we avoid them?

**Comment by jdries** [comment]
replacing as a quickfix is fine if you are blocked
Did someone look into why it is taking so long, or perhaps even log a bug? (If concrete info exists...)

**Comment by KanerLev** [comment]
Great.
To the best of my info, other than me no one else looked at it as (as I acted on it only yesterday afternoon).
Per concrete info: I only have this: when mermaids are replaced with png, PR are created at a normal speed and they don't fail. With this, I reckon I can go with a bug report in here: https://github.com/quarto-dev/quarto-cli/issues/new/choose

**Comment by KanerLev** [comment]
Hi again @jdries, 

Looking at https://github.com/quarto-dev/quarto-cli/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
I don't think I'll go with reporting it as a bug. I'm not able to complete it up to that standard at the moment.

Instead, if you refuse this PR, I'll take a note of it to troubleshoot it myself.

**Review by jdries — APPROVED** [review]
approved because I'm going to be away, so don't want to delay.
I do think there's probably a reason why this rendering takes too long, immediately abandoning this way of working might be drastic.

**Comment by KanerLev** [comment]
Noted, thanks. 
Note: The situation has been stable since I created this PR. Therefore change of plans: I'm closing without merging.

**Comment by KanerLev** [comment]
I had to remove the mermaid: https://github.com/eu-cdse/documentation/pull/571 again as a hotfix.
I created an issue on it: https://github.com/eu-cdse/documentation/issues/572

**Pull request closed without merging**
