### PR TITLE
openEO federation migration from staging

### PR DESCRIPTION
**Pull request by Pratichhya**
Due to some current version issue in the staging branch, in the PR, we have migrated all the changes made in #486

### CODE REVIEW

**Comment by Pratichhya** [comment]
@JanssenBrm , could you please confirm if all migrated changes have been transferred well? 
 
Also, I hope you are aware of pages such as   ../APIs/openEO/federation/backends/design.html, the sidebar collapse as it is not included in the yml

**Comment by Pratichhya** [comment]
Please let me know if it is fine to merge then I can go ahead with that

**Comment by Pratichhya** [comment]
@JanssenBrm a kind reminder 😃

**Comment by JanssenBrm** [comment]
Looks good! Thank you @Pratichhya . Meanwhile I've merged the documentation.

**Pull request merged**
